---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Domain
metadata:
  name: domain-enabled-true
spec:
  cloudCredentialsRef:
    cloudName: devstack-admin
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    description: Sample Domain
    enabled: true
    

